before_install: |
  pushd /tmp
  curl -Lo - http://download.camlcity.org/download/godi-skylift-20121022.tar.gz | tar xz
  cd godi-skylift-20121022
  cp $TRAVIS_BUILD_DIR/tools/log_to.rb .
  sed -i.bak -e 's/>>bootstrap.log 2\>\&1/2\>\&1 \| tee -a bootstrap.log/' bootstrap_stage2
  sudo ./bootstrap --batch
  ls -R /opt/godi
  popd

install: |
  godi_console perform -build godi-ocaml-all
  godi_console perform -build godi-omake

build: true
